name: "Nix CI"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v22
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - uses: cachix/cachix-action@v12
        with:
          name: gtrunsec
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build Doc
        run: |
          nix develop .#docs -c mkdoc
          mkdir -p ./docs/publish/public/posts/ilograph-simple
          cp ./diagrams/ilograph/simple.html ./docs/publish/public/posts/ilograph-simple/index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: ./docs/publish/public
